//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import Foundation

 //MARK: Router -
protocol ___VARIABLE_productName:identifier___Routing: class {
    func navigateToAnotherModule()
}

//MARK: Builder -
protocol ___VARIABLE_productName:identifier___Building: ModuleBuilding {
}

protocol ModuleBuilding: class {
    func buildModule() -> VanMoof.VMFModule?
}

//MARK: Presenter -
protocol ___VARIABLE_productName:identifier___Presenting: class {

    var interactor: ___VARIABLE_productName:identifier___InteractorInputProtocol? { get set }
}

//MARK: Interactor -
protocol ___VARIABLE_productName:identifier___InteractorOutput: class {

    /* Interactor -> Presenter */
}

protocol ___VARIABLE_productName:identifier___InteractorInput: class {

    var presenter: ___VARIABLE_productName:identifier___InteractorOutputProtocol?  { get set }

    /* Presenter -> Interactor */
}

//MARK: View -
protocol ___VARIABLE_productName:identifier___ViewProtocol: class {

    var presenter: ___VARIABLE_productName:identifier___Presenting?  { get set }

    /* Presenter -> ViewController */
}
