//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Juanpe Catalán @JuanpeCMiOS
//

import UIKit

class ___VARIABLE_productName:identifier___Presenter: ___VARIABLE_productName:identifier___Presenting, ___VARIABLE_productName:identifier___InteractorOutput {

    weak private var view: ___VARIABLE_productName:identifier___Viewable?
    var interactor: ___VARIABLE_productName:identifier___InteractorInput?
    private let router: ___VARIABLE_productName:identifier___Routing

    init(view: ___VARIABLE_productName:identifier___Viewable, interactor: ___VARIABLE_productName:identifier___InteractorInput?, router: ___VARIABLE_productName:identifier___Routing) {
        self.view = view
        self.interactor = interactor
        self.router = router
    }

}
