//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

class ___VARIABLE_productName:identifier___Builder: ___VARIABLE_productName:identifier___Building {

    func buildModule() -> VanMoof.VMFModule? {
    	return nil 
    }
}
