//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

import Foundation

//MARK: Router -
protocol ___VARIABLE_productName:identifier___Routing: class {
    func navigateToAnotherModule()
}

//MARK: Builder -
protocol ___VARIABLE_productName:identifier___Building: ModuleBuilder {
}

protocol ModuleBuilder: class {
    func buildModule() -> VanMoof.VMFModule?
}

//MARK: Presenter -
protocol ___VARIABLE_productName:identifier___Presenting: class {

}

//MARK: Interactor -
protocol ___VARIABLE_productName:identifier___Interacting: class {

  var presenter: ___VARIABLE_productName:identifier___Presenting?  { get set }
}

//MARK: View -
protocol ___VARIABLE_productName:identifier___Viewable: class {

  var presenter: ___VARIABLE_productName:identifier___Presenting?  { get set }
}
