//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  Template generated by Sameh Mabrouk https://github.com/iSame7
//

import UIKit

class ___VARIABLE_productName:identifier___ViewController: UIViewController, ___VARIABLE_productName:identifier___Viewable {

	var presenter: ___VARIABLE_productName:identifier___Presenting?

	override func viewDidLoad() {
        super.viewDidLoad()
    }

}
